"use client"

import {
  MessageSquare,
  Settings,
  User,
  FileText,
  Upload,
  Download,
  Search,
  Plus,
  X,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronsUpDown,
  Menu,
  MoreHorizontal,
  Eye,
  EyeOff,
  Copy,
  Trash,
  Edit,
  ExternalLink,
  Github,
  Twitter,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock,
  Star,
  Heart,
  Share,
  Bookmark,
  Flag,
  AlertCircle,
  CheckCircle,
  XCircle,
  Info,
  HelpCircle,
  Loader2,
  LoaderPinwheelIcon as Spinner,
  type LucideIcon,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  chat: MessageSquare,
  settings: Settings,
  user: User,
  file: FileText,
  upload: Upload,
  download: Download,
  search: Search,
  add: Plus,
  close: X,
  check: Check,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronUp: ChevronUp,
  chevronsUpDown: ChevronsUpDown,
  menu: Menu,
  moreHorizontal: MoreHorizontal,
  eye: Eye,
  eyeOff: EyeOff,
  copy: Copy,
  trash: Trash,
  edit: Edit,
  externalLink: ExternalLink,
  github: Github,
  twitter: Twitter,
  mail: Mail,
  phone: Phone,
  mapPin: MapPin,
  calendar: Calendar,
  clock: Clock,
  star: Star,
  heart: Heart,
  share: Share,
  bookmark: Bookmark,
  flag: Flag,
  alertCircle: AlertCircle,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  info: Info,
  helpCircle: HelpCircle,
  loader: Loader2,
  spinner: Spinner,
}
